language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: reyi_claros@hotmail.com
  password:
    secure: uVfhvzYcUVE0vfeIl7r242u58Er4MKrX4iGqBT5NqT6PUjETH4GfhLnuMeYhGzdB8wTfduVxgYOFJSXHUtEYPRA8vWM4rLqFcv67g+iMJ16E3IiEaPhZxS2UfZH/tzp19+U3JX/icpUl1OrDqHgqV5XePpD6y6Qsr1T+iN5n5SPSM2O/2nh7Jzh0xp26QzdzgsAM3UAhoJqxHpkVIMZAxwn4dTdu6RriGWpqWy1BCQudVnzjgkJ5k1+qPxmXokQoybFLZkVenjmtiu+RogLPW/evMXiW52GpkKkLGJ07OPWcBCnJcuN2V5+C62twOFcTudgQUfdcemNP/U533WxpIu7hyIbn2mbLoDdGUByDNfjKbxV29xr1ZGhWbr5Rc5y+jDTy/8QSRFa4AhpkpILadj4jF0SdwOMgK6VmLFVfqV7TXlP0K5tg96bQNXqKEF+DVHS8cMfKpUzX6F+R864wVTVAVvSSWeEO5jEE1JA64HAPTo855uFYfK9vAuFmopq0OuKso4WYiHCTG5aVABUXS86uM4TjosSgfOwXHU+AvwLOQ2YQPdNqQ+PExw4uEqDzPH5JhT7A61M86Q5qVfKsTih0HkJ0Hyzrsz56QbPMqWzj3btqdVXY2ngJphFITNTqZjjYMk7/3CiSWIILd2Dvx+l8xkoGgCAR+C7wm2xsrIs=
  organization: ads2019i
  space: development
