language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: reyi_claros@hotmail.com
  password:
    secure: s0EYS1XIEBdw+c5Z5a06UV64Kr1e2sA5CrEweIeNZtmLtwEQgri15YxmlsMyKR7J13bUOV7xNHF+vUXkAiqRpgsC2nzoSX45ZXMBzuS2fCnjnoybXbczK/hVscA0XmAnAeGdjouY6tce718GQ4+PD4UUMTHMcHHQS16QlHbhDsM4xkUVb1uBZ1KRHPyrALb6vYBENfLYWb2m+kI8bbLMHHBwE14tM+JfsrhqjsDrwLKrcDYr6bxkDJ9WsnngoIwaWyDygiS1dhfhXc9639qxQMR5D81QSfvt35g+IB5aYqplyjnSpurXVmEHVnamOryss0IMDPL5G+j9FNKTKvJTf8Prgs6BHstSkFyRYMJVxHnpvwJExqa+3YL8XA67tZFfZUDUc4QttRLVUmSh2MhuaymI1m9TwKlzcXC05nGk93ICt+65fdOjdqRMDA9SlRcGr+RK9mrB2SmY16mvn0EzCc7QHfUWeoppnNqITNSl5PPmsxGNnhvsqIqkIXlB0b48hteAfl2OACJMPGAnuFyQydf001oQdRcx9cIupzQj2gbEDyJ8stwTUIwGh+jxRTtbhkVm2T6JbKhAxLnQm48a0zo6bocd4T02QkDwdlTtZUuE0oT0kdwzV8M9PmlpoiOTwQk7wrOCH8JTxwIX9bMPzZL/dBv3YQllu0KNEGx2P2o=
  organization: ads2019i
  space: development
  on:
    repo: rclaros/banking-api