language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: reyi_claros@hotmail.com
  password:
    secure: raV/h+yVks+aibFuAiqFGTZFJaQVv5pFjRuwdFiXbZoYjFPLr90gXQam+NnYgSsqAHT/UlQCeo0zpI4UlIXtyQyUsj7Y35U7mbuyM3kZbb5OAKakJ5Gnk2TzmB5VIkVCS1KwdO2+zNcowyYRhgwRR0zmPLZrzBnOEjvAKYan2YidW6R5GJwZ12MNOgjBZDa5Huh4DDwATL+uzhZqITS2tVTgcxQUvD4gDv+S+2fQqxNYwdPvF3u/YXxPwoa960PVjV+suWxX6JrJqymGOETTeNwNpXEMVKioUG7gsRz0pQ8njbgOek4UKZrf4rSUkCKKJlZ+f//6H21oRvEJ5b9TrqehzTbrxNE7K3msShCYIYH7lize9sGQe6QG8pvnv62/j4c0AdKkvX/hwyp2YpDRfEW4ADnff2hWjEsxKN+VkyN26r6ESVlZHhinOqLpI1giVXnZQzVX9TcJgumVOyNHxUSEY2YdMIGde8iOO1A9I0mBEOMbleqf8kLaAWljHtEvYGX1M1l5GAm5jGalUdj++SQ0jnmxx98jMjUemeZVg+zUAFiY0Yg9gt+GbcvmKEtCUM2LQvpJ9EP409FMvqyu7lTbCLsKo4eetRuSJ1oaXYYx6mbHk90GJzvUYF38s5ssu2AzFi9ZQ+E1kZDT2I4J6cutHR+Aniyc3q3h/G606Hc=
  organization: ads2019i
  space: development
  on:
    repo: rclaros/banking-api
