language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: reyi_claros@hotmail.com
  password:
    secure: Jz3DAewmXZZCkdkxV5096ZoAHOQ/NG0M/R32JD9/Ma+mLGkWQvVHJQGxoQ09WL73+PnKCeK7GZS8y+tr8KDpfz569ndrqBbjd+AnAudcCoVhW2kVPoID3zDN5baInkVB3xT+72FeINq3mA2N3uKdriglqIA86xMeYyFB5JA6xs1jQn1RBGPbmSx+u3aJ31DFilCPov8yq+DIzNrzoxw4fTIigx2jcUIx8lFuRaiS+DIx1SfuI/93K9fu8ozHHlu5rDoi63tYoLF/++bqVrLc4ETRt9O5RKn5kwqHun4xvJ/s+ddCqAH/d6JzbJdJwR3UmuUw32qIEJbxR7V+QvT7AcjZ/oJ/RhWsRCWznYf/Ff1y8ZzRTISO7WStVq3xiBQNcQ2tf5iJ14KwrjDxs28+/EBwXyN3qTn5sF6SnU1gQTRjMulQ4zFN2gAU/L8R1BdGOd1pY6uZYf0dkNhT9pF3RD7tJbA5+qe5mP3f9j10m/nzO73izMhzOg7i1bqRYOCS7mMsaZSCjhg8gb/18AkpEkJLH4ivZFJRCgpe+YhMOvVDYZBdfRcbj/1JAiP5/udwiIR2w77Nv3opzELoxGdEW2iiB6uoZ1V3itiWScEnjpP3Lo96446wY0xjQM4W9sX7I7vvY8kpH/hVipozQm/5ad2EFUZZeUBruilMJkgi8L0=
  organization: ads2019i
  space: development
