language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: reyi_claros@hotmail.com
  password:
    secure: GGgvKEyf06x4jqzbQ62u6NCm3og5l5vljFMUbbb9KPBjiXUK1GSqJYo1uoYkmU5JDbSj3xAZk35ip34u0QK/kQHF3fJ7PqHEEVqyXSSqtqW97MOoMWCt+GFAK93AGsKYJC9fBCepHIqKNVQxJBZmc9k+Y4bjq2SEUV70FZrVCt6gdpIWGLWBflCl5k7VBozsnDR3NvxWtJ7r8z60gJUmORflABn2W4J4iptg7JA23cAM4OnZcdeb1Rn0KiPr4n4Ufy4+5MtG5reigdFK4/B983e4kB/7RJFjgL5nYUi+g3r7heAcOHAETuvJQcr46arA97llHbX0/7trsIXkpH7/vy4/I0Yh1CsBE4vD7NBBsL2Sun+kHk7adcgfQOhM9bcsMDdMXbyMtHKXYVqb3b83+3wQvNp+KRgKVK+UfzLaKSEaFWpyb85tzaYrB6KlllVFg0dB/BYZ/AtwUl+s4MQncdNkVSOmbUP+DQLm/6cW5ISiGrpy4oWzVzqChWjiPejsl9/4qF3+NYQhF0+YieisHVBgvG8kFxvYNP/hU+hsmqZ1tcMGQN+ROfv72eJVTAh9re2SsQWLgA5RBdUxy1VqNRMtGsqG9p5iKN7dy9tdy3tzQjQ9miP7NY8PYJmoMq6s/ifzictUE0fsetcyVlgNhLysZGsF3tagsP8cYEyylLA=
  organization: ads2019i
  space: development
