language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: reyi_claros@hotmail.com
  password:
    secure: sSY/HQc8fi8X9SmZ7jUFQHhjhOJtRER+kLUGU4e99CUW5clfFLMnWWv3j5Q2aFSMyYgW8CeoPpd9eG2rxUvIpQ2h2NRXNGBnBhghRkQ4Jptr9rMZyJAo4gkcHrWx1JMAYdVp9df/AOjSTg4CNNH/G1zlwX+SPhSEe4Fyw4cGUWbe4Y54mgBpDIzt3gr8Bsez0hMtFo83SVcewi2S8TLUvgZe4ww2mDQD/QOgRtshjkPaPqwzBYq26aOZ8E/bhe3jdooJppII6lPxefcyckqkbVQFRX9WnOB4Nitu4tAB6UxIrE5W/U07JTntAXWMv2rMAdKZ37AFFlS95xtfVqkPNnFSRfwqZtMLRRmWQxySjF2/xSs5uecAETi451CT6oI/JEaFhckApJcoKct0N6myeSjLlsiuK2srjDw+L5D7HdJ0CUko1a9esf7zTeOXRJWcrC+X2Cy5ydDN45rymm/neEYVNn4EYf4EA5OYunGorJx3RsxB7cnWLkHWYfGgM3IHePlzHvmj1xd3dwU5Vqj3p0AmMfICdrkIYTy3I4jPsX7U8USA/N8AnRqx/X5xk8YIFxxQXgbJ8Tt2H2z8D5lUMvsPuFH4k4gzw8JLPyWV/NddqrXoa506PVIRg6UpXUEh2aFVjncqFRWx0XBFGZSBEhDSCUxIYCQvuoZFMyo6VVQ=
  organization: ads2019i
  space: development
