language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: reyi_claros@hotmail.com
  password:
    secure: eRP9udk0ILnv6UZ6WGi40NKs+Fr0E5bAg1+qmoSM6lOxf+ElKHzK4zBTV4yT4VYRW/1WnVaxkvTjOxaotbbzp0dMgjXlDPopDXxhNgYIjq4Mg3WiVJ1ImE8fpGupVNoKxBs3s0OZecEHWYrqqngICozRV6I/E2XJif+CBZbbRZYSJ0tahtxs2u4nTkyCWaE55oLli+0fjyvodKPSTbmtLPrzHmyf9UKc3e/5/Az1YJzSqYwZxi8VNif5vqWgkE2cl/QYxqu5Bn4LOxWV6haGY6rmTEQUpSSy9gHdOMyedYlcznBbemLj0Dfr83u0tgYwyiwZy2QpgIQMbHU5qZSfowBYkuGDCO2luhhqMl2IvsUxJ43JobrUK9ZBz2Ea9EX9bsJ86rs9fvryE4GcT8qFV31xt+5CM8vPY5aaZZ+22lxhF08/8g65Udc6KeCMl2Pqlb07QWwonJh8+QLCvSAPsrPBQO9tFw6ydZnBYW6Uab0Eax5fQfJ7QHnCbgEOmFgxGnL146O8JKNzroYNeG9/BLTrDnNWNJKdJ88LAul7h35r2j32yo+bpjzjPAmpR+/9mf+bT3r9PEmzqqu8beaU6tJhwCq4MTyj/Uf0QoYDpeoyLyKar17d8yMFQuNXK1PDkJen6Ny6EpdDwwmgEiH/QZrTcH8jDn+fZqO0yHD3beM=
  organization: ads2019i
  space: development
