language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: reyi_claros@hotmail.com
  password:
    secure: ZDaby5VtFzS+Txf9Ua2yrJ+irFOLCw23vWmTfZlJBA3w5ywxhVnCQLMvP6MLvaI9Vv4Gjcj1sBwhAJB9wtXDJ8vCv8Q702+NkvrDX/MMwUbzYM2zT6GgzGkE5Nvh9y42yRSSSc0cZlS4XYCTBSi7ajYtoE0zdtaKKXfguIHzToTQxMFPV5TbnjSIUOhFTqJoBl+Iy1S75UFS7lI2j6v21YIYDUz0Cf6y4SCpeCXkkteFhGICkz/YzxIMXKmomBnlWhTKSKVsaD4y5efS4TLCfuZA6broUKXj63NwiHVdywYSOXkERHK+uXfDkt1lnWcZAbjEmQV9pcJ8Wuqjbh3Y/1a2HevgaG6u+oKxOds8aCTNccsQphCwH49eqrBQzzRmQ/du9CeZU1M0icN8AyuSBzv96gZQqfM4CDsm94XQpxscvcxTr9EQZJ9WWynhvp31gSUfB5FcyX5WQtdNH9ual02D9BNz7LTdIrAWVo9E/A7UQSwE/GxLL7+fefmzq/gHHDy/CmpHMYjAdDVB7tuKaXoi+I4c8JZFDCI24nOdbS300wnnHkEeSlmVJ4caICWaFK78MRMB8AD5hs2eH0cRLuqekk3LrAklJ2OqMDDihrT9dEHRgzTFKHX/bM9Qfb8zVg1Dh2vj1vpyP2e2QDyIgGqEYnfsDITX2lLkZ1Fe390=
  organization: ads2019i
  space: development
