language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: reyi_claros@hotmail.com
  password:
    secure: g3OtAJYqGXuw8obw2akIo9VjFhqRtpts92kuwupia6M2QpOD8derYtbZkU7VYL6kEJjZXXBzIVMZNJvNQ27RGzIgIvqUS9cJbe5NHC1BLcQM72R7k+THHbulJTTdeC5mLglbh3dkfIFjUjZGgfqWdX3heECEXF9B38iYcOpZ+w0/8dT36oc5D0WHptSDD/1bceWKvaSkoT4PVF5iGlEMi7P561qpwdHuCXIPyM34hSamWfStmf6Lw3RRQvrIlRrcZB5J6wthI6avOKhtVpv2Tq5n/Gc6sTSn73C94ONuhxIHwpVL2BKC/nKHKfwJL1Oti/rXeqGqkUTlC1eab4rgRJqc/3v8kWMWq1hbVLy95KcdBuYlvuXWO2Qce+Rwh3Ed/NZJap2l19pI15cUVYtBcRA0D4UAnwZRsIKX/ObJFDGQ8RDLAiTsQBjZ9ittzX7uEFn2TqCgXYw6wkOL9tHMR9sCI2mfA8C4AzsQlv7ksIyQnPaYZlKwNGjDwJD0kU1vZaSwfTQven3Wojje7GDtuo46FHeJ2HRkpaa9pA+EgfyO3F1I6hdsL4lrV2kIeEsZp3RY5pCog3tQLNklJs9UtBqPHSfKILpdad1ILMQhAlPuB5LHaGpjXM+B6IFokI1tcp5It4iw+QK+UsqDJPlo+bFMYJqE/MLXHopmgjjRbOw=
  organization: ads2019i
  space: development
