language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
deploy:
  provider: cloudfoundry
  username: reyi_claros@hotmail.com
  password: 
    secure: ZMfpeaeb32ZbT+5y5xEpf+6+gBqDHGb+doqFBclc4E3kFx+qhV6U2Ro2JUcOpDOlA9RRWJxFfC8nIELfRGigtM6KvlcbpBLjLHeNwqUFxieMltXltgbvy6cZ30Ww7BDYwQP5Wcgf7KoNJLYIF/CnwmakHN0N8fQiD3hA57T55UVnJ1aXBP7B8MYj69ffYf/bYHBcUGHfIRcdVZZD3s9k6YrhCbchEdVrlvDpn6MXV5MAwx+jBAiGelEBMtDUOnJ9juFZ6klhqTYizgQgsW9sllFFnzxQslL7/ZNo0g7q7uZv99qVBm2+0HHLuXot8xTzF3dkn8uF3LWg3o0hcd+OKjCrb2CMujbQV7vUnjSSu6ao6zBGqpUf2XrkTVJk0FZzZbNPRs6mo/b+5u9N0L5ePY9c6kmT0pDqUwW8Brqmb8JHO0I3tx1lqmvydDZod6s90yane2OZEgM07g6An0G/2E7GqJqYr3/wHQbrk5rzDE9w7GsTg8azZLG5Bw/JJdEoVyeJ5jKVrDy0mNQm6FxcOvKCrVqcpdcYeamMShsHjdymR41i5APjK7B3Zo8xWaelpYAbp07aiBas9Z+W9na8WHsdkbYnkSI2Qgolm2+Va1qs6IA/HozLTksjh0qTDmPMkb0UT/bTsnQi0q/IUTYbqYGowpEXwukAOm17zVu4aSY=
  api: https://api.run.pivotal.io
  organization: ads2019i
  space: development
