language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: reyi_claros@hotmail.com
  password:
    secure: P7/yRJrXkVZOFeCZ8w7PYPfX/W1HtknuMbQkC6kli9vmpYFVX8pU+NYZEPtlHvuRZIDmDPC4hoXd0E+VVejsXuFoSE5o2LGKiTAAHKV6aORhle9dD7l30/S+gL2lbHyOeRDjdMvxT8VqRf1Xaps4gi2WTUk+cRgd3OC+LO4QzTfZ5ASzZH1ELOUoGJtGOcxwY9FjYfQ9UY+87wLvKjJ3Gt0qFyMO0szP7Vw+0RBUPbWflKw6CLjDYgsGwJvMzUZ9bDF8kLOSxWbCTqPkboSx9ypcM/uzqasF60AnNrkASehb/MICJJBJynJldHb3hKgLLUI3uHLnqx+6RwVa1ocNMX2pa9YJ24GJ3siyM+OSAk79lp604soc+U51C5uXykl/1KBMBfrPJn2tul7Eo2b31PbUmglutgpXneZc8fieMqyQDS60sYinfLJ5OKIt7DueZFrBAzMLXpoqb97FKUSpSryrVcUKoeh+UwJIQEKoZMwLzIUIt9jnLr2AWicNQPLdQZ4lO+JEhKbYGtBSndQA2Mnbv9sqVZU5FU1O90hFWn8hrzE0VbJxhVG99hCj8LEqy5WFuQ47TioA+MvuETMyG5jxBv/vxjN9f60YskbxzCMbEtuKEAGuxR8gI0g6UmTiCW+C9Tv4lIfpUTkLvsS/EwqlSCf6Xi9b4pJ41G0K7KQ=
  organization: ads2019i
  space: development
  on:
    repo: rclaros/banking-api