language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: reyi_claros@hotmail.com
  password:
    secure: ldKkZDM4IY2wW8K+Y10oS1XCFQSxgsfm5jN+Mh+OJcXQ4lu3Hk3Y7V3hvgau3TSRSLsPfQ81O+N9j2YVJc/xuk9biPyq52n5Az7zwWQB3tpTm3i1sBKCo+Rv5G+HoIx+e2MNn1vVhEtDv/K3Rp2VwT4V2OQASI7sehfxVtyfMPTe+JRd5YJt6LEQBgoSfQH0szZJy/sE/LNFOFQ8HiMOMXffyjBTF/rNDQXt4pFdAM4u1HiZvl5dBfMyphqQ9AdAyw7b6RZdkX9zDZi7qvBxrKi6tsJDgr2JJZ5ciEfGJfi4iFzf86fXU5MfO6xlECNfyZOuNtXaTuC9paCyNBJxGkvr40JAoi4YeaHY2WO8MwyfKe9CuADvhZ9Z7fzp6hGSfoL6/wjAKzmMoa5jFSSRxVWukiPJAp5PbkxOCrSjq/i4v7Yjz7ZP/JlJ+cIT5JqeEJoB97XudUfVlhW0D/zuYDsN+zNgGiUtKOGq+0A0bYfwf7GBi37BVb4X19qQ70c+mJPX+o6itBWEfVEeQUoxgJctxkv0torSADSjw9zgGsctQlbkFZP3JWaTVOR/1ibF5RR1OaltyS1h1ohDWsMKk/tVSKsKrQO7g9cLLk6K4U+6PGP5/Jw7wG++UOz0H0mgbg9AIaXKFz/hzEzTrZuI3ZmBvZUuExOCokZW7nyGZ2A=
  organization: ads2019i
  space: development
