language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: reyi_claros@hotmail.com
  password:
    secure: WtRJJTzB0SnkY7WM3ZuEVNaZr7TzjE94mUjmMf/EWFJLxkoP7aXeNu6uJcs9ja+rA2xrkeOZLiQ6iS3O4mCV22rRIybJ1e8diNrqiikh3PfGTe0Tc02q7DsYT0eJhJyle6TMf/oNQibXuDdx2R87G8DD/EzNFWEAhmOvpCnp7LHdYAHX39C51a6etPyP7mI35KznjgyleXc6mEXOZGHAJVYvmiLKi1Nz1DpO/UhJUHtwN4gykxBaWWfcbj1El7wr7o4tDGS4wEc1BkruHdTyF/PCMJLGZfpcx3d6kkuN3m2xo0KVs/TQ+lEWtZWLxUyvswJgASfUtY4AAH5R0HEMjYvVx1KCaS021VzjzzFAk5L4mC6aIEqztksoERZigxB9RVAHdfcIfseH/I/HR2mHZ+OJ48xq4xlppStNyRgBWU84Bwf/WCRaKLECSzkMpumzNmT8xBUzauH7ETCdVGEw39ttZ1lzNr+Vwb6OD+Y8XrBxinvCK1eCH2wZ7+PYq2i9eknm1qFrXkT1pZyowzgkpzHtpUv7Ft2xPF33U1ycSvU/KWKxbozWyA2r1XH/Jq8HJ6PkHyPLW3s/LdlyygpZDbQx88qa9WXPYWh/9Keznzwk9LhwCW5LpORzJpSYobhQHj7dmT+2yC1fI4FueXBi/KgV+8exVSgf/RHsNtJJWZU=
  organization: ads2019i
  space: development
  on:
    repo: rclaros/banking-api