language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: reyi_claros@hotmail.com
  password:
    secure: OjG+tJGe4FuauXIvvHb2KVFWkvyzec75IWz67K+jvgJOeINQ9wv+XBOe44GMxQSMUfLdR2SAkSmBuT/QmUcrEbnGjUsEnqAMnQ5299zrGrhOLFy4l3g5AdjhK0nEr7E6wu8ZQEtSBabJO5fKFGwQpr7FNDoh8c2FZdidVJ8I4s4bQ8UNPv8Z4OiWaL+Aj4CFUvZ1KTiQzRluhcpTYH4rltK1pk+vwcWLzbFDysF9CYtB/hm+hUbPQ8Q8D/mWy5owUZxVevSIzZ67xrPCGnxTv+sdN3nMk2mcS1I/vofDbpW5wyKb+n/HtAHzS19cBjYeXAHNXEew3tar3tght5WQqEKo9N3XrcPJp/7hVtTWPaK/GpKQM5lZXzTxc9TJ0drvfKSjvNOaHR+UxBAN/ndnLhYi8m3/upLvAHLGvDcO7ej14q60fyDYxcK2fo8T+sWVv9qm2cb4jf+NSHEgRBtWItAc9T77x9xOAM1pFL7VgyDSgCca5T8CpNLbaTGMg6j8gitVE7y/DBcrbBsYE98ac7733Z/OIL48qcvkzr0fR5PIg6Rfas4ryCvPJloztxmj7ia6kEW8DqVBDiR8AcstiL1n4nI0l2QVCBYeF8AkeXBk4GS3NOyYCghwYUkkQA9SNRn7A8XBUe4DfYYe30+EdDkeQa3BPXA8m8YAvbQzyC8=
  organization: ads2019i
  space: development
