language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: reyi_claros@hotmail.com
  password:
    secure: wuYXQ6zA0V7TBfjc601yNtXbpkg2vGAXAn3kYkqG3m98q+g+L8qdy+8tQA38z0ZEGzQKDuvgA6WZ9mpA1Fu0I/1YTP6iVGyVRD6eK/088nVuv6736Q20tEE7Xx/r5mbTlWPb5Jir8ne5uwUxI4iV2lj6qZ+v20wKdztGzPVMBmCXuujXu9lXakgIFWzYuK6YY89PpC1Ma1pbbuuKL/Wi0oEOMBx5ZLOQ/H9r9Gilx5BlcPcf8L0RbE4jTD3TlNUWjoXx5EUY9w5mjQQl59ucDeIWoak5fCHvOZbADa8ryGct9uPBB9UQf2m91bKClBqZZMhJIMGgrNjIluWHPNWBNT8dSgDCmkmPevCstsOTwECdPGxEXQfWiKOz0byQ9w4HOvrTsE23vGlg6TbVuyHrkJmSrVrRYuj+a8QvBZBU/tUJegp0+WEf+RsuLBQA+mbSbiC26oeCM4t7/thdCttQgtzP+YVz7c5Dg5yJC8GN+aYnNMxDsmQNOREejmLwed/4h0VF4cIDIha0rKrhanUGVxo1GDT/r+ZDip197wiH81soeExlueaq5O42qVVyEpUOcxN/M2Fyr1De2kgG8PwIP8V4O8zsPm6jFmFScnCz4EvXsnm4bor748aIgEfEuReJvdNqLTyuo3pjYXuKeIqapaIyyW/gGB7Fa3vpa71uO8w=
  organization: ads2019i
  space: development
  on:
    repo: rclaros/banking-api